# Generated by Django 4.0.6 on 2024-01-31 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_todo_delete_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='post',
        ),
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 1, 31, 16, 59, 5, 406536)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(),
        ),
    ]
